In [71]:
from sklearn.datasets import load_boston
from scipy import stats
from scipy.stats import zscore
import pandas as pd
import numpy as np
import seaborn as sns
boston = load_boston()

In [2]:
data= boston.data

In [4]:
cols = boston.feature_names

In [7]:
boston_df = pd.DataFrame(data=data, columns=cols)

In [23]:
boston_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [26]:
z = np.abs(boston_df.apply(zscore))

In [33]:
boston_df_new = boston_df[(z < 3).any(axis=1)]

In [22]:
q1 = boston_df.quantile(0.25)

In [12]:
q3 = boston_df.quantile(0.75)

In [13]:
IQR = q3-q1

In [18]:
cond1 = boston_df < q1 - 1.5*IQR

In [17]:
cond2 = boston_df > q3 + 1.5*IQR

In [35]:
boston_df_new[~(cond1 | cond2).any(axis=1) ].shape

(274, 13)

In [36]:
df_insurance = pd.read_csv('Downloads/insurance.csv')

In [39]:
df_insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [41]:
df_insurance['charges_log']  = np.log(df_insurance['charges'])

In [42]:
df_insurance.head()

   age     sex     bmi  children smoker     region      charges  charges_log
0   19  female  27.900         0    yes  southwest  16884.92400     9.734176
1   18    male  33.770         1     no  southeast   1725.55230     7.453302
2   28    male  33.000         3     no  southeast   4449.46200     8.400538
3   33    male  22.705         0     no  northwest  21984.47061     9.998092
4   32    male  28.880         0     no  northwest   3866.85520     8.260197

In [44]:
charges_max = df_insurance.charges_log.max()
charges_min = df_insurance.charges_log.min()

In [45]:
from sklearn.preprocessing import StandardScaler

In [47]:
sc = StandardScaler()
boston_df = sc.fit_transform(boston_df)

In [48]:
boston_df

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [49]:
sample_data_df = pd.read_csv('Downloads/sample_data.csv')

In [51]:
sample_data_df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [54]:
sample_data_df.shape

(205, 26)

In [58]:
sample_data_df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [64]:
cylinder_col = sample_data_df['cylindernumber'].value_counts().index.tolist()

In [ ]:
cleanup_nums = {'doornumber':{'one':1, 'two':2, 'three':3,'four':4, 'five'}

In [77]:
sample_data_df_1 = pd.get_dummies(sample_data_df, columns=['carbody', 'drivewheel'], prefix=['body','drive'], drop_first=True)

In [78]:
sample_data_df_1

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,enginelocation,wheelbase,carlength,carwidth,...,peakrpm,citympg,highwaympg,price,body_hardtop,body_hatchback,body_sedan,body_wagon,drive_fwd,drive_rwd
0,1,3,alfa-romero giulia,gas,std,two,front,88.6,168.8,64.1,...,5000,21,27,13495.000,0,0,0,0,0,1
1,2,3,alfa-romero stelvio,gas,std,two,front,88.6,168.8,64.1,...,5000,21,27,16500.000,0,0,0,0,0,1
2,3,1,alfa-romero Quadrifoglio,gas,std,two,front,94.5,171.2,65.5,...,5000,19,26,16500.000,0,1,0,0,0,1
3,4,2,audi 100 ls,gas,std,four,front,99.8,176.6,66.2,...,5500,24,30,13950.000,0,0,1,0,1,0
4,5,2,audi 100ls,gas,std,four,front,99.4,176.6,66.4,...,5500,18,22,17450.000,0,0,1,0,0,0
5,6,2,audi fox,gas,std,two,front,99.8,177.3,66.3,...,5500,19,25,15250.000,0,0,1,0,1,0
6,7,1,audi 100ls,gas,std,four,front,105.8,192.7,71.4,...,5500,19,25,17710.000,0,0,1,0,1,0
7,8,1,audi 5000,gas,std,four,front,105.8,192.7,71.4,...,5500,19,25,18920.000,0,0,0,1,1,0
8,9,1,audi 4000,gas,turbo,four,front,105.8,192.7,71.4,...,5500,17,20,23875.000,0,0,1,0,1,0
9,10,0,audi 5000s (diesel),gas,turbo,two,front,99.5,178.2,67.9,...,5500,16,22,17859.167,0,1,0,0,0,0
10,11,2,bmw 320i,gas,std,two,front,101.2,176.8,64.8,...,5800,23,29,16430.000,0,0,1,0,0,1
11,12,0,bmw 320i,gas,std,four,front,101.2,176.8,64.8,...,5800,23,29,16925.000,0,0,1,0,0,1
12,13,0,bmw x1,gas,std,two,front,101.2,176.8,64.8,...,4250,21,28,20970.000,0,0,1,0,0,1
13,14,0,bmw x3,gas,std,four,front,101.2,176.8,64.8,...,4250,21,28,21105.000,0,0,1,0,0,1
14,15,1,bmw z4,gas,std,four,front,103.5,189.0,66.9,...,4250,20,25,24565.000,0,0,1,0,0,1
15,16,0,bmw x4,gas,std,four,front,103.5,189.0,66.9,...,5400,16,22,30760.000,0,0,1,0,0,1
16,17,0,bmw x5,gas,std,two,front,103.5,193.8,67.9,...,5400,16,22,41315.000,0,0,1,0,0,1
17,18,0,bmw x3,gas,std,four,front,110.0,197.0,70.9,...,5400,15,20,36880.000,0,0,1,0,0,1
18,19,2,chevrolet impala,gas,std,two,front,88.4,141.1,60.3,...,5100,47,53,5151.000,0,1,0,0,1,0
19,20,1,chevrolet monte carlo,gas,std,two,front,94.5,155.9,63.6,...,5400,38,43,6295.000,0,1,0,0,1,0
20,21,0,chevrolet vega 2300,gas,std,four,front,94.5,158.8,63.6,...,5400,38,43,6575.000,0,0,1,0,1,0
21,22,1,dodge rampage,gas,std,two,front,93.7,157.3,63.8,...,5500,37,41,5572.000,0,1,0,0,1,0
22,23,1,dodge challenger se,gas,std,two,front,93.7,157.3,63.8,...,5500,31,38,6377.000,0,1,0,0,1,0
23,24,1,dodge d200,gas,turbo,two,front,93.7,157.3,63.8,...,5500,24,30,7957.000,0,1,0,0,1,0
24,25,1,dodge monaco (sw),gas,std,four,front,93.7,157.3,63.8,...,5500,31,38,6229.000,0,1,0,0,1,0
25,26,1,dodge colt hardtop,gas,std,four,front,93.7,157.3,63.8,...,5500,31,38,6692.000,0,0,1,0,1,0
26,27,1,dodge colt (sw),gas,std,four,front,93.7,157.3,63.8,...,5500,31,38,7609.000,0,0,1,0,1,0
27,28,1,dodge coronet custom,gas,turbo,two,front,93.7,157.3,63.8,...,5500,24,30,8558.000,0,0,1,0,1,0
28,29,-1,dodge dart custom,gas,std,four,front,103.3,174.6,64.6,...,5000,24,30,8921.000,0,0,0,1,1,0
29,30,3,dodge coronet custom (sw),gas,turbo,two,front,95.9,173.2,66.3,...,5000,19,24,12964.000,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,176,-1,toyota corona,gas,std,four,front,102.4,175.6,66.5,...,4200,27,32,9988.000,0,1,0,0,1,0
176,177,-1,toyota corolla,gas,std,four,front,102.4,175.6,66.5,...,4200,27,32,10898.000,0,0,1,0,1,0
177,178,-1,toyota mark ii,gas,std,four,front,102.4,175.6,66.5,...,4200,27,32,11248.000,0,1,0,0,1,0
178,179,3,toyota corolla liftback,gas,std,two,front,102.9,183.5,67.7,...,5200,20,24,16558.000,0,1,0,0,0,1
179,180,3,toyota corona,gas,std,two,front,102.9,183.5,67.7,...,5200,19,24,15998.000,0,1,0,0,0,1
180,181,-1,toyota starlet,gas,std,four,front,104.5,187.8,66.5,...,5200,20,24,15690.000,0,0,1,0,0,1
181,182,-1,toyouta tercel,gas,std,four,front,104.5,187.8,66.5,...,5200,19,24,15750.000,0,0,0,1,0,1
182,183,2,vokswagen rabbit,diesel,std,two,front,97.3,171.7,65.5,...,4800,37,46,7775.000,0,0,1,0,1,0
183,184,2,volkswagen 1131 deluxe sedan,gas,std,two,front,97.3,171.7,65.5,...,5250,27,34,7975.000,0,0,1,0,1,0
184,185,2,volkswagen model 111,diesel,std,four,front,97.3,171.7,65.5,...,4800,37,46,7995.000,0,0,1,0,1,0
185,186,2,volkswagen type 3,gas,std,four,front,97.3,171.7,65.5,...,5250,27,34,8195.000,0,0,1,0,1,0
186,187,2,volkswagen 411 (sw),gas,std,four,front,97.3,171.7,65.5,...,5250,27,34,8495.000,0,0,1,0,1,0
187,188,2,volkswagen super beetle,diesel,turbo,four,front,97.3,171.7,65.5,...,4500,37,42,9495.000,0,0,1,0,1,0
188,189,2,volkswagen dasher,gas,std,four,front,97.3,171.7,65.5,...,5500,26,32,9995.000,0,0,1,0,1,0
189,190,3,vw dasher,gas,std,two,front,94.5,159.3,64.2,...,5500,24,29,11595.000,0,0,0,0,1,0
190,191,3,vw rabbit,gas,std,two,front,94.5,165.7,64.0,...,5500,24,29,9980.000,0,1,0,0,1,0
191,192,0,volkswagen rabbit,gas,std,four,front,100.4,180.2,66.9,...,5500,19,24,13295.000,0,0,1,0,1,0
192,193,0,volkswagen rabbit custom,diesel,turbo,four,front,100.4,180.2,66.9,...,4500,33,38,13845.000,0,0,1,0,1,0
193,194,0,volkswagen dasher,gas,std,four,front,100.4,183.1,66.9,...,5500,25,31,12290.000,0,0,0,1,1,0
194,195,-2,volvo 145e (sw),gas,std,four,front,104.3,188.8,67.2,...,5400,23,28,12940.000,0,0,1,0,0,1
195,196,-1,volvo 144ea,gas,std,four,front,104.3,188.8,67.2,...,5400,23,28,13415.000,0,0,0,1,0,1
196,197,-2,volvo 244dl,gas,std,four,front,104.3,188.8,67.2,...,5400,24,28,15985.000,0,0,1,0,0,1
197,198,-1,volvo 245,gas,std,four,front,104.3,188.8,67.2,...,5400,24,28,16515.000,0,0,0,1,0,1
198,199,-2,volvo 264gl,gas,turbo,four,front,104.3,188.8,67.2,...,5100,17,22,18420.000,0,0,1,0,0,1
199,200,-1,volvo diesel,gas,turbo,four,front,104.3,188.8,67.2,...,5100,17,22,18950.000,0,0,0,1,0,1
200,201,-1,volvo 145e (sw),gas,std,four,front,109.1,188.8,68.9,...,5400,23,28,16845.000,0,0,1,0,0,1
201,202,-1,volvo 144ea,gas,turbo,four,front,109.1,188.8,68.8,...,5300,19,25,19045.000,0,0,1,0,0,1
202,203,-1,volvo 244dl,gas,std,four,front,109.1,188.8,68.9,...,5500,18,23,21485.000,0,0,1,0,0,1
203,204,-1,volvo 246,diesel,turbo,four,front,109.1,188.8,68.9,...,4800,26,27,22470.000,0,0,1,0,0,1
204,205,-1,volvo 264gl,gas,turbo,four,front,109.1,188.8,68.9,...,5400,19,25,22625.000,0,0,1,0,0,1